apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogengineapp
  namespace: default
  labels:
    app: blogengineapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogengineapp
  template:
    metadata:
      labels:
        app: blogengineapp
    spec:
      containers:
      - name: blogengineapp
        image: [IMAGEN-BACKEND-DOCKER-REGISTRY]
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
        resources:
          requests:
            cpu: 1
            memory: 128Mi
          limits:
            cpu: 2
            memory: 512Mi
