apiVersion: v1
kind: Service
metadata:
  name: blogengineapp
  namespace: default
  labels:
    app: blogengineapp
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 2005
    targetPort: 80
  selector:
    app: blogengineapp