apiVersion : apps/v1
kind: Deployment
metadata:
  name: "interviewscluster"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "interviewscluster"
  template:
    metadata:
      labels:
        app: "interviewscluster"
    spec:
      containers:
        - name: "interviewscluster"
          image: "interviewsacr.azurecr.io/interviewscluster"
          ports:
          - containerPort: 80