apiVersion : apps/v1
kind: Deployment
metadata:
  name: "interviewscluster-1539"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "interviewscluster-1539"
  template:
    metadata:
      labels:
        app: "interviewscluster-1539"
    spec:
      containers:
        - name: "interviewscluster-1539"
          image: "interviewsacr.azurecr.io/interviewscluster"
          ports:
          - containerPort: 80