apiVersion: v1
kind: Service
metadata:
    name: "interviewscluster-1539"
    labels:
        app: "interviewscluster-1539"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "interviewscluster-1539"